---
- name: "EC2 Destroyer part 1"
  hosts: all
  tasks:
  - name: "Attempting to gracefully terminate connection and grade user"
    block:
    - name: "Erasing user authorized_keys"
      become: true
      file:
        path: "/home/{{ login }}/.ssh/authorized_keys"
        state: absent

    ## Violent disconnect, no exception.
    - name: "Terminating user SSH connection"
      shell: "sudo -u {{ login }} pkill -9 ssh"
      changed_when: false
    ## This will try to kill every SSH connection, which some will go permission denied.
      ignore_errors: yes

    - name: "Stating all file before copying"
      stat:
        path: "{{ item.format(user=user, login=login) }}"
      loop: "{{ file_to_copy }}"
      register: r

    - name: "Using DARK ARTS to get the total size, and filtering the nonexistant file out"
      set_fact:
        file_sizetotal: "{{ range(0,r.results|length)|map('extract', r.results)|selectattr('stat.size', 'defined)|map(attribute='stat.size')|sum }}"
        filtered_file_to_copy: "{{ range(0,r.results|length)|map('extract', r.results)|selectattr('stat.exists')|map(attribute='stat.path')|flatten }}"

    - name: "Creating tarball file to copy"
      shell: "tar -czvf - {{ filtered_file_to_copy | join(' ') }} | base64 -w0"
      when: file_sizetotal|int <= file_sizelimit|int
      register: f

    - name: "Copying file to another host"
      awx.awx.job_launch:
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
        name: "The Copy Master"
        job_type: "run"
        organization: "Default"
        extra_vars:
          user: "{{ user }}"
          login: "{{ login }}"
          content: "{{ f.stdout }}"
        wait: no

    - name: "Grading resource"
      awx.awx.job_launch:
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
        name: "{{ grade_template }}"
        inventory: "EC2 Managed"
        limits: "{{ user }}.{{ domain }}"
        organization: "Default"
        extra_vars:
          user: "{{ user }}"
          login: "{{ login }}"
          domain: "{{ domain }}"
        credentials:
          - "{{ user }}.{{ domain }} SSH"
        wait: no
      when: grade

    ## This job will always destroy whether the above task has successfully ran or not
    always:
    - name: "Destroying EC2"
      awx.awx.job_launch:
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
        name: "EC2 Destroy"
        inventory: "AWX localhost baremetal"
        organization: "Default"
        extra_vars:
          login: "{{ login }}"
          domain: "{{ domain }}"
          user: "{{ user }}"
        credentials:
          - "AWX unprivileged token"
          - "AWS token"
          - "AWX SSH"
        wait: no
