---
- name: "Generate initial templates"
  hosts: all
  become: false
  tasks:

  - name: "Set working directory variable (user readability)"
    set_fact: "user={{ firstname[:3] | lower }}-{{ lastname[:6] | lower }}"

  - name: "Set user variable (user readability)"
    set_fact: "login={{ firstname[0] | lower }}{{ lastname[:6] | lower }}"

  - name: "Creating context directory"
    file:
      name: "{{ user }}"
      state: directory
      mode: 0750

  - name: "Creating empty terraform state"
    file:
      name: "{{ user }}/terraform.tfstate"
      state: touch
      mode: 0644

  - name: "Cloning Terraform Git"
    git:
      repo: "https://github.com/SaltyDev42/OSXP-Terraform-SX"
      accept_hostkey: yes
      clone: yes
      force: no
      dest: "OSXP-Terraform-SX"

  - name: "Generate keypair SSH"
    openssh_keypair:
      force: false
      state: present
      type: ed25519
      comment: "{{ email }}"
      path: "{{ user }}/user.key"
    register: user_pub

  - name: "Generate keypair for AWX connection"
    openssh_keypair:
      force: false
      state: present
      type: ed25519
      comment: "awx@{{ inventory_hostname }}"
      path: "{{ user }}/awx.key"
    register: awx_pub

  - name: "Get private awx key"
    slurp:
      src: "{{ user }}/awx.key"
    register: awx_key

  - name: "Get private user key"
    slurp:
      src: "{{ user }}/user.key"
    register: user_key

  - name: "Generating terraform.auto.tfvars"
    template:
     src: terraform.auto.tfvars.j2
     dest: "{{ user }}/terraform.auto.tfvars"
     mode: 0400

    ## OLD TERRAFORM MODULE IS OUTDATED FOR CURRENT TERRAFORM VERSION
  - name: "Provisioning EC2"
    no_log: false
    community.general.terraform:
      force_init: yes
      lock: yes
      project_path: "OSXP-Terraform-SX/"
      state: present
      workspace: "{{ user }}"
      variables_files:
        - "/home/{{ ansible_user }}/{{ user }}/terraform.auto.tfvars"
    environment:
      AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  - name: "Create SSH credentials for newly created host"
    awx.awx.credential:
      controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
      controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
      name: "{{ user }}.{{ domain }} SSH"
      description: "SSH connection for backdoor"
      user: ec2_manager
      state: present
      credential_type: "Machine"
      inputs:
        username: "rocky"
        ssh_key_data: "{{ awx_key.content | b64decode }}"
        become_method: "sudo"
        become_username: "root"

  - name: "Create HOST in EC2 Managed"
    awx.awx.host:
      controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
      controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
      name: "{{ user }}.{{ domain }}"
      inventory: "EC2 Managed"
      description: "EC2 Managed by AWX, used by {{ firstname }} {{ lastname }}"
      enabled: yes
      state: present

  - name: "Waiting for HOST to be ready"
    wait_for:
      host: "{{ user }}.{{ domain }}"
      port: 22
      state: started
      sleep: 5

  - name: "Launching Resource provisioner"
    awx.awx.job_launch:
      controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
      controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
      name: "{{ resource_template }}"
      inventory: "EC2 Managed"
      limit: "{{ user }}.{{ domain }}"
      organization: "Default"
      extra_vars:
        user: "{{ user }}"
        login: "{{ login }}"
        domain: "{{ domain }}"
      credentials:
        - "{{ user }}.{{ domain }} SSH"
      wait: no
    
  ## adding 30 sec difference, ansible is not very quick and we are dealing with HTTP and Ansible,
  ## there will be time deltas.
  - name: "Set destroy instance {{ idle_timeout }} minute late"
    set_fact: "destroy_time={{'%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch|int+idle_timeout|int*60+30) }}"

  - name: "Launch check activity scheduler"
    awx.awx.schedule:
      controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
      controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
      name: "Check activity {{ user }}"
      description: "Check activity for instance used by {{ firstname }} {{ lastname }}"
      inventory: "EC2 Managed"
      extra_data:
        login: "{{ login }}"
        user: "{{ user }}"
        alive_timeout: "{{ alive_timeout }}"
        domain: "{{ domain }}"
        grade_template: "{{ grade_template }}"
        file_to_copy: "{{ file_to_copy }}"
        file_sizelimit: "{{ file_sizelimit }}"
      credentials:
        - "{{ user }}.{{ domain }} SSH"
        - "AWX unprivileged token"
      job_type: "run"
      limit: "{{ user }}.{{ domain }}"
      state: present
      enabled: yes
      unified_job_template: "The EC2 Checker"
      organization: "Default"
      rrule: "{{ query('awx.awx.schedule_rrule', 'minute', every=1, timezone='UTC', end_on=idle_timeout|string, start_date=scheduled_time)}}"

  - name: "Launch scheduled EC2 destroyer"
    awx.awx.schedule:
      controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
      controller_oauthtoken: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"
      name: "Destroyer of EC2 {{ user }}"
      description: "Timeout, instance is destroyed, DO NOT TOUCH OR BEHAVIOR IS UNDEFINED"
      inventory: "EC2 Managed"
      credentials:
        - "{{ user }}.{{ domain }} SSH"
        - "AWX unprivileged token"
      job_type: "run"
      limit: "{{ user }}.{{ domain }}"
      extra_data:
        login: "{{ login }}"
        user: "{{ user }}"
        domain: "{{ domain }}"
        grade: no
        grade_template: "{{ grade_template }}"
        file_to_copy: "{{ file_to_copy }}"
        file_sizelimit: "{{ file_sizelimit }}"
      enabled: yes
      unified_job_template: "The EC2 Destroyer"
      organization: "Default"
      rrule: "{{ query('awx.awx.schedule_rrule', 'none', timezone='UTC', start_date=destroy_time)}}"
